# Generated by Django 3.1.2 on 2020-10-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('CreatedAt', models.DateTimeField(verbose_name='video created')),
                ('LengthInSecond', models.FloatField()),
                ('ViewCount', models.IntegerField()),
                ('YoutubeId', models.CharField(max_length=100)),
            ],
        ),
    ]
