# Generated by Django 3.1.2 on 2020-10-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='YoutubeId',
            new_name='VideoId',
        ),
    ]
